body:
  - type: markdown
    attributes:
      value: Thank you for investing your time on improving this project! Please fill out the forms below to the best of your ability.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief summary of the issue and how the pull request is fixing it.
    validations:
      required: true
  - type: dropdown
    id: pr-type
    attributes:
      label: PR Type
      multiple: true
      options:
        - New feature
        - Bug fix
        - Performance optimization
        - Refactoring
        - Code style optimization
        - Branch merge
        - Other (please describe in description)
  - type: textarea
    id: issues
    attributes:
      label: Fixes Issue(s)
      description: Issue Number(s)
    validations:
      required: false