name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2
        with:
          dotnet-version: 10.0.x

      - name: Restore Dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-build --no-restore --verbosity normal --coverage --coverage-output-format cobertura --coverage-settings coverage.runsettings --results-directory ./coverage

      - name: Prepare coverage files for Codecov
        run: |
          # Rename coverage files to .xml extension that codecov recognizes
          counter=1
          for file in ./coverage/*.cobertura.xml; do
            if [ -f "$file" ]; then
              mv "$file" "./coverage/coverage${counter}.xml"
              counter=$((counter + 1))
            fi
          done

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        if: github.actor != 'dependabot[bot]'
        with:
          directory: ./coverage
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
