name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CollectCoverage: true
      CoverletOutputFormat: opencover

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --no-restore

      - name: Run Unit Tests
        run: dotnet test ./src --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - uses: codecov/codecov-action@v3
        with:
          flags: unittests
          fail_ci_if_error: true
