name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@4861e015da555e86a72b862892aba6c2b93e6891
        with:
          pr-mode: true
          args: |
            --baseline qodana.sarif.json
            --linter "jetbrains/qodana-cdnet:2026.1"
            --within-docker false
          use-caches: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1052839006 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json